apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: nodejs-prometheus-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
